load section .text from file
starting from 0x1000526c

sp := 0xffffccf1     # arbitrarily concretize the stack pointer

heap<32> := 0x55555555

# arbitrarily concretize and set the return address of the function
return_address<32> := 0x100052b8

# exploration goal and actions
reach return_address such that true then print formula

# exit with error if postcond is not verified
replace return_address by
    exit(1)
end

r0:={v0}
@[{v0},1]:={v1}
@[{v0}+1,1]:={v2}
@[{v0}+2,1]:={v3}
@[{v0}+3,1]:={v4}
@[{v0}+4,1]:={v5}
@[{v0}+5,1]:={v6}
@[{v0}+6,1]:={v7}
@[{v0}+7,1]:={v8}
@[{v0}+8,1]:={v9}
r1:= uext32 {v10}
r2:= uext32 {v11}


