load section .text from file
starting from 0x100052bc

sp := 0xffffccf1     # arbitrarily concretize the stack pointer

heap<32> := 0x55555555

# arbitrarily concretize and set the return address of the function
return_address<32> := 0x100052f2

# exploration goal and actions
reach return_address such that true then print formula

# exit with error if postcond is not verified
replace return_address by
    exit(1)
end

r0:={v0}
@[{v0}+1,1]:={v3}
@[{v0}+2,2]:={v4}
@[{v0}+4,4]:={v5}
ff<32> := @[{v0}+8,4]
@[ff,4]:={v6}
@[ff+4,2]:={v7}


tmpff<32> := @[{v0}+8, 4]

bitsff<16> := uext16 ({v9} * 0x0f) + (({v8} & 0x7f))
@[tmpff+6, 2] := bitsff
@[tmpff+8, 2] := {v10}
@[tmpff+10, 2] := {v11}


tmp<8> := @[{v0}, 1]
tmp := tmp & 0xfc
bits<8> := ({v1} & 0x01) + (({v2} & 0x01) * 2)
tmp := tmp | bits
@[{v0}, 1] := tmp

r1:=uext32 {v12}
r2:=uext32 {v13}
r3:=uext32 {v14}
@[sp,4]:={v15}
@[sp,4]:= uext32 {v16}
@[sp,4]:={v17}
@[sp,4]:= uext32 {v18}

