load section .text from file
starting from 0x10005180

sp := 0xffffccf1     # arbitrarily concretize the stack pointer

heap<32> := 0x55555555

# arbitrarily concretize and set the return address of the function
return_address<32> := 0x100051b4

# exploration goal and actions
reach return_address such that true then print formula

# exit with error if postcond is not verified
replace return_address by
    exit(1)
end

r0:={v0}
@[{v0},1]:={v1}
@[{v0}+1,1]:={v2}
@[{v0}+2,1]:={v3}


tmp<8> := @[{v0}, 1]
tmp := tmp & 0xc0
bits<8> := ({v4} & 0x02) + ({v5} & 0x02)*2 + (({v6} & 0x02) * 4)
tmp := tmp | bits
@[{v0}+3,1]:= tmp

@[{v0}+4,2]:={v7}
@[{v0}+6,1]:={v8}

r1:={v9}
r2:=uext32 {v10}
