
load section .text from file
starting from 0x1000564c

sp := 0xffffccf1     # arbitrarily concretize the stack pointer

heap<32> := 0x55555555

# arbitrarily concretize and set the return address of the function

return_address<32> := 0x10005670

# exploration goal and actions
reach return_address such that true then print formula

replace 0x10002b7c (dest, src, size) by
    for i<32> in 0 to size do
        @[dest+i, 1] := @[src+i,1]
    end
    return dest
end



# exit with error if postcond is not verified
replace return_address by
    exit(1)
end


r0:={v0}
@[{v0},4]:={v1}
@[{v0}+4,2]:={v2}
@[{v0}+8,2]:={v5}
@[{v0}+10,2]:={v6}
tmpff<16> := uext16 ({v4} * 0x0f) + (({v3} & 0x7f))
@[{v0}+6,2]:= tmpff

r1:={v7}
r2:= uext32 {v8}
r3:= uext32 {v9}
@[sp,1]:= {v10}
