
load section .text from file
starting from 0x100050d0

sp := 0xffffccf1     # arbitrarily concretize the stack pointer

heap<32> := 0x55555555

# arbitrarily concretize and set the return address of the function
#return_address<32> := 0x1000073a
return_address<32> := 0x100050ea

# exploration goal and actions
reach return_address such that true then print formula

# exit with error if postcond is not verified
replace return_address by
    exit(1)
end

r0:= uext32 {v0}
r1:= {v1}

@[{v1},1]:= {v2} & 0xff
@[{v1}+1,1]:={v3} & 0xff
