load sections .rodata from file

starting from 0x9a70

rsp := 0xffffffffffffccf1     # arbitrarily concretize the stack pointer

heap<64> := 0x5555555555555555

df := 0x0

# arbitrarily concretize and set the return address of the function
return_address<64> := 0x9a9e

# exploration goal and actions
reach return_address such that rax = 0x0 then print formula

# exit with error if postcond is not verified
replace return_address by
    exit(1)
end

#@[0x000800f0, 8] := 0x7ffff7aa5120 as exit
replace 0x8210 by
    exit(rdi)
end

#@[0x00080110, 8] := 0x7ffff7aa5122 as rand
replace 0x8250 by
    tmp<64> := rand(0, 10)
    return tmp
end

#@[0x00080080, 8] := 0x7ffff7aa5124 as calloc
replace 0x8130 by
    res<64> := heap
    heap := heap + (rdi * rsi)
    if rdi * rsi = 0 then
        return 0
    else
        return res 
    end
end

#@[0x000801c8, 8] := 0x7ffff7aa5125 as memset
replace 0x8100 by
    for i<64> in 0 to rdx do
        @[rdi+i, 4] := esi 
    end
    return rdi
end

#@[0x00080000, 8] := 0x7ffff7aa5126 as free
replace 0x8030 by
    return
end

replace 0x1d250 by
    for i<64> in 0 to rsi do
        @[rdi+i, 4] := 0
    end
    return rdi
end

replace 0x1d250 by
    for i<64> in 0 to rsi do
        @[rdi+i, 4] := 0
    end
    return rdi
end

rdi := {v0}
rsi := {v1}
@[rsi+8,4]:={v2}
@[rsi+13,8]:= uext64 {v3}
rdx := uext64 {v4}


